/**
 * Regenerates `src/lib/hp/ionian-land.ts` — the baked land geometry the
 * decorative sea-shimmer punches out of the sea (see `src/lib/hp/sea-shimmer.ts`).
 *
 *   download → clip → drop-islets → simplify → clean → round → bake
 *
 * Source: Natural Earth 1:10m land vector (public domain — naturalearthdata.com,
 * mirrored at github.com/nvkelso/natural-earth-vector). The coastline never
 * changes, so this is a one-off / rarely-run script, NOT part of `npm run build`.
 *
 *   npm run build:ionian-land
 *
 * The ~10 MB source download is cached under `scripts/.cache/` (git-ignored) so
 * re-runs work offline.
 */
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import mapshaper from "mapshaper";
import { format, resolveConfig } from "prettier";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..");
const CACHE_DIR = join(HERE, ".cache");
const RAW_CACHE = join(CACHE_DIR, "ne_10m_land.geojson");
const OUT_FILE = join(REPO_ROOT, "src/lib/hp/ionian-land.ts");

const SOURCE_URL =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_land.geojson";

// Clip window = MAP_PAN_BOUNDS in SocialMap.tsx ([36.2, 19.4]–[38.9, 23.5])
// plus ~0.3° padding on every side, so land-meets-bbox seams sit outside the
// pannable area. [west, south, east, north].
const CLIP_BBOX = [19.1, 35.9, 23.8, 39.2] as const;

// Visvalingam retention. 40% keeps bays and headlands close enough to the real
// shore that the wave edge doesn't chord across inlets or clip peninsulas at
// the shimmer's upper zoom band; the baked file is still ~15 KB / ~4 KB gzip.
// (Higher would only start to matter past zoom 12, where the layer is hidden.)
const SIMPLIFY_PERCENT = 40;

// Drop any land part below this area. Ithaca (~90 km²) is the smallest of the
// four islands we keep (Zakynthos, Kefalonia, Ithaca, Lefkada); everything
// smaller renders as a pinhole speck in the wave fill. `this.area` is m².
const MIN_LAND_AREA_M2 = 8e7;

// Coordinate rounding: 5e-4° ≈ 45 m ≈ 1.5 px at zoom 12 (the shimmer's max),
// fine enough that the wave edge reads as a smooth line rather than steps.
const COORD_PRECISION = 0.0005;

type Ring = [number, number][];
type Polygon = Ring[];

async function loadSource(): Promise<string> {
  if (existsSync(RAW_CACHE)) {
    console.log(`• using cached source ${RAW_CACHE}`);
    return readFile(RAW_CACHE, "utf8");
  }
  console.log(`↓ downloading ${SOURCE_URL}`);
  const res = await fetch(SOURCE_URL);
  if (!res.ok) {
    throw new Error(
      `Download failed: ${res.status} ${res.statusText}. ` +
        `If this environment has no network access, drop a copy of ne_10m_land.geojson at ${RAW_CACHE}.`,
    );
  }
  const text = await res.text();
  await mkdir(CACHE_DIR, { recursive: true });
  await writeFile(RAW_CACHE, text);
  console.log(`• cached source (${(text.length / 1_048_576).toFixed(1)} MB)`);
  return text;
}

function collectPolygons(geojson: {
  features: { geometry: { type: string; coordinates: unknown } | null }[];
}): Polygon[] {
  const polygons: Polygon[] = [];
  for (const feature of geojson.features) {
    const geometry = feature.geometry;
    if (!geometry) continue;
    if (geometry.type === "Polygon") {
      polygons.push(geometry.coordinates as Polygon);
    } else if (geometry.type === "MultiPolygon") {
      polygons.push(...(geometry.coordinates as Polygon[]));
    }
  }
  return polygons;
}

function formatPolygons(polygons: Polygon[]): string {
  const ring = (r: Ring) => `[${r.map(([x, y]) => `[${x}, ${y}]`).join(", ")}]`;
  const polygon = (p: Polygon) => `  [\n${p.map((r) => `    ${ring(r)}`).join(",\n")}\n  ]`;
  return `[\n${polygons.map(polygon).join(",\n")}\n]`;
}

async function main(): Promise<void> {
  const source = await loadSource();

  const commands = [
    "-i in.geojson",
    `-clip bbox=${CLIP_BBOX.join(",")}`,
    "-explode",
    `-filter 'this.area > ${MIN_LAND_AREA_M2}'`,
    `-simplify visvalingam ${SIMPLIFY_PERCENT}% keep-shapes`,
    "-clean",
    "-filter-slivers min-area=1e6",
    `-o out.geojson precision=${COORD_PRECISION} format=geojson`,
  ].join(" ");
  console.log(`⚙ mapshaper ${commands}`);

  const output = (await mapshaper.applyCommands(commands, {
    "in.geojson": source,
  })) as Record<string, string>;
  const geojson = JSON.parse(output["out.geojson"]);
  const polygons = collectPolygons(geojson);

  const ringCount = polygons.reduce((n, p) => n + p.length, 0);
  const coordCount = polygons.reduce((n, p) => n + p.reduce((m, r) => m + r.length, 0), 0);

  const banner =
    `// AUTO-GENERATED by scripts/build-ionian-land.ts — do not edit by hand.\n` +
    `// Regenerate with: npm run build:ionian-land\n` +
    `//\n` +
    `// Source: Natural Earth 1:10m land vector (public domain — naturalearthdata.com).\n` +
    `// Clipped to [${CLIP_BBOX.join(", ")}] (MAP_PAN_BOUNDS + ~0.3° pad), islands below\n` +
    `// ~${Math.round(MIN_LAND_AREA_M2 / 1e6)} km² dropped, Visvalingam-simplified to ${SIMPLIFY_PERCENT}%, coords rounded to ${COORD_PRECISION}°.\n` +
    `// ${polygons.length} polygons · ${ringCount} rings · ${coordCount} coords.\n`;

  const body =
    `export type LandRing = [number, number][];\n` +
    `export type LandPolygon = LandRing[];\n\n` +
    `/**\n` +
    ` * GeoJSON-style nesting: polygons → rings → [lng, lat]. The first ring of\n` +
    ` * each polygon is the outline; any further rings are interior holes.\n` +
    ` */\n` +
    `export const IONIAN_LAND_POLYGONS: LandPolygon[] = ${formatPolygons(polygons)};\n`;

  const prettierConfig = await resolveConfig(OUT_FILE);
  const formatted = await format(`${banner}\n${body}`, {
    ...prettierConfig,
    parser: "typescript",
  });
  await writeFile(OUT_FILE, formatted);
  console.log(
    `✓ wrote ${OUT_FILE} — ${polygons.length} polygons, ${coordCount} coords ` +
      `(${(Buffer.byteLength(formatted) / 1024).toFixed(1)} KB)`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
