import { createHash } from "node:crypto";

import {
  AUTHORS,
  EVENTS,
  PLACES,
  POSTS,
  ROUTES,
  STORIES,
  VIBE_CHIPS,
  type Comment,
} from "./hp-seed-data";

type SqlValue = string | number | null | string[];

function sql(value: SqlValue): string {
  if (value === null) return "null";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "null";
  if (Array.isArray(value)) return `array[${value.map(sql).join(", ")}]::text[]`;
  return `'${value.replaceAll("'", "''")}'`;
}

function uuidFromSeed(seed: string): string {
  const hash = createHash("sha256").update(seed).digest("hex");
  const chars = hash.slice(0, 32).split("");
  chars[12] = "4";
  chars[16] = ((Number.parseInt(chars[16], 16) & 0x3) | 0x8).toString(16);
  return [
    chars.slice(0, 8).join(""),
    chars.slice(8, 12).join(""),
    chars.slice(12, 16).join(""),
    chars.slice(16, 20).join(""),
    chars.slice(20, 32).join(""),
  ].join("-");
}

function insertRows(
  table: string,
  columns: string[],
  rows: SqlValue[][],
  conflict: string,
  updateColumns = columns.filter(
    (column) =>
      !conflict
        .split(",")
        .map((c) => c.trim())
        .includes(column),
  ),
): string {
  if (rows.length === 0) return "";

  const assignments = updateColumns
    .map((column) => `${column} = excluded.${column}`)
    .join(",\n    ");
  const values = rows.map((row) => `  (${row.map(sql).join(", ")})`).join(",\n");

  return [
    `insert into public.${table} (${columns.join(", ")})`,
    "values",
    values,
    `on conflict (${conflict}) do update set`,
    `    ${assignments};`,
  ].join("\n");
}

function slug(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function authorIdForComment(comment: Comment): string | null {
  const id = comment.author.toLowerCase();
  return AUTHORS.some((author) => author.id === id) ? id : null;
}

const seededPostComments = POSTS.flatMap((post) =>
  post.comments.map((comment, index) => ({
    id: uuidFromSeed(`post-comment:${post.id}:${index}:${comment.author}:${comment.text}`),
    postId: post.id,
    authorId: authorIdForComment(comment),
    authorName: comment.author,
    text: comment.text,
    sortOrder: index,
  })),
);

const sections = [
  "-- Generated by scripts/generate-supabase-seed.ts. Do not edit by hand.",
  "begin;",
  insertRows(
    "authors",
    ["id", "name", "type", "avatar_url"],
    AUTHORS.map((author) => [author.id, author.name, author.type, author.avatarUrl]),
    "id",
  ),
  insertRows(
    "places",
    [
      "id",
      "name",
      "greek_name",
      "type",
      "area",
      "x",
      "y",
      "lat",
      "lng",
      "pulse",
      "mood",
      "crowd",
      "budget",
      "best_time",
      "tags",
      "short",
      "image_url",
      "hotness",
      "comment_count",
      "recent_post_count",
      "status",
      "sort_order",
    ],
    PLACES.map((place, index) => [
      place.id,
      place.name,
      place.greekName,
      place.type,
      place.area,
      place.x,
      place.y,
      place.lat,
      place.lng,
      place.pulse,
      place.mood,
      place.crowd,
      place.budget,
      place.bestTime,
      place.tags,
      place.short,
      place.imageUrl,
      place.hotness,
      place.commentCount,
      place.recentPostCount,
      place.status,
      index,
    ]),
    "id",
  ),
  `delete from public.place_avatars where place_id in (${PLACES.map((place) => sql(place.id)).join(", ")});`,
  insertRows(
    "place_avatars",
    ["place_id", "position", "avatar_url"],
    PLACES.flatMap((place) =>
      place.avatars.map((avatarUrl, index) => [place.id, index, avatarUrl] as SqlValue[]),
    ),
    "place_id, position",
  ),
  insertRows(
    "posts",
    [
      "id",
      "author_id",
      "place_id",
      "kind",
      "display_time",
      "text",
      "tags",
      "likes_count",
      "image_url",
      "sort_order",
    ],
    POSTS.map((post, index) => [
      post.id,
      post.authorId,
      post.placeId,
      post.kind,
      post.time,
      post.text,
      post.tags,
      post.likes,
      post.imageUrl,
      index,
    ]),
    "id",
  ),
  `delete from public.comments where id in (${seededPostComments.map((comment) => sql(comment.id)).join(", ")});`,
  insertRows(
    "comments",
    ["id", "target_type", "post_id", "author_id", "author_name", "text", "sort_order"],
    seededPostComments.map((comment) => [
      comment.id,
      "post",
      comment.postId,
      comment.authorId,
      comment.authorName,
      comment.text,
      comment.sortOrder,
    ]),
    "id",
  ),
  insertRows(
    "events",
    ["id", "title", "place_id", "display_time", "price", "vibe", "tags", "sort_order"],
    EVENTS.map((event, index) => [
      event.id,
      event.title,
      event.placeId,
      event.time,
      event.price,
      event.vibe,
      event.tags,
      index,
    ]),
    "id",
  ),
  insertRows(
    "routes",
    [
      "id",
      "title",
      "author_id",
      "lede",
      "duration",
      "budget",
      "tags",
      "image_url",
      "comment_count",
      "saves_count",
      "sort_order",
    ],
    ROUTES.map((route, index) => [
      route.id,
      route.title,
      route.authorId,
      route.lede,
      route.duration,
      route.budget,
      route.tags,
      route.imageUrl,
      route.commentCount,
      route.saves,
      index,
    ]),
    "id",
  ),
  `delete from public.route_stops where route_id in (${ROUTES.map((route) => sql(route.id)).join(", ")});`,
  insertRows(
    "route_stops",
    ["route_id", "position", "display_time", "place_id", "title", "body"],
    ROUTES.flatMap((route) =>
      route.stops.map((stop, index) => [
        route.id,
        index,
        stop.time,
        stop.placeId,
        stop.title,
        stop.body,
      ]),
    ),
    "route_id, position",
  ),
  insertRows(
    "stories",
    ["id", "label", "place_id", "position"],
    STORIES.map((story, index) => [
      `story-${slug(story.label)}`,
      story.label,
      story.placeId,
      index,
    ]),
    "id",
  ),
  insertRows(
    "vibe_chips",
    ["id", "label", "position"],
    VIBE_CHIPS.map((label, index) => [`vibe-${slug(label) || index}`, label, index]),
    "id",
  ),
  "commit;",
  "",
];

process.stdout.write(sections.filter(Boolean).join("\n\n"));
