export type PlaceType =
  "beach" | "culture" | "nature" | "food" | "local" | "village" | "night" | "sunset";

export type PlaceStatus = "quiet" | "active" | "popular" | "busy";

export interface Author {
  id: string;
  name: string;
  type: "LOCAL EDITOR" | "LOCAL" | "TOURIST" | "BUSINESS" | "EVENT" | "EDITOR";
  avatarUrl: string;
}

export interface Comment {
  author: string;
  text: string;
}

export interface Place {
  id: string;
  name: string;
  greekName: string;
  type: PlaceType;
  area: string;
  x: number;
  y: number;
  lat: number;
  lng: number;
  pulse: number;
  mood: string;
  crowd: string;
  budget: string;
  bestTime: string;
  tags: string[];
  short: string;
  imageUrl: string;
  hotness: number;
  commentCount: number;
  recentPostCount: number;
  status: PlaceStatus;
  avatars: string[];
}

export interface Post {
  id: string;
  authorId: string;
  placeId: string;
  kind: "spot" | "tip" | "event" | "photo";
  time: string;
  text: string;
  tags: string[];
  likes: number;
  imageUrl: string;
  comments: Comment[];
}

export interface EventItem {
  id: string;
  title: string;
  placeId: string;
  time: string;
  price: string;
  vibe: string;
  tags: string[];
}

export interface RouteStop {
  time: string;
  placeId: string;
  title: string;
  body: string;
}

export interface RouteItem {
  id: string;
  title: string;
  authorId: string;
  lede: string;
  duration: string;
  budget: string;
  stops: RouteStop[];
  tags: string[];
  imageUrl: string;
  commentCount: number;
  saves: number;
}

const RAW_PLACES = [
  {
    id: "ancient-olympia",
    name: "Ancient Olympia",
    greekName: "Αρχαία Ολυμπία",
    type: "culture",
    area: "Olympia",
    x: 63,
    y: 48,
    pulse: 7,
    mood: "historic but still iconic",
    crowd: "medium",
    budget: "€€",
    bestTime: "late afternoon",
    tags: ["culture", "unesco", "walk", "history"],
    short: "Ancient ruins, golden light, and a surprisingly good late-afternoon wander.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20the%20archaeological%20site%20of%20Ancient%20Olympia%2C%20Greece%20%2851223832734%29.jpg?width=1200",
  },
  {
    id: "olympia-stadium",
    name: "Olympia Stadium",
    greekName: "Στάδιο Ολυμπίας",
    type: "culture",
    area: "Olympia",
    x: 65,
    y: 49,
    pulse: 5,
    mood: "quiet flex",
    crowd: "low",
    budget: "€€",
    bestTime: "morning",
    tags: ["ancient", "walk", "photo", "calm"],
    short: "The ancient stadium. Simple, huge, silent. Feels better than expected.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Olympia%20the%20stadium.jpg?width=1200",
  },
  {
    id: "olympia-museum",
    name: "Archaeological Museum of Olympia",
    greekName: "Αρχαιολογικό Μουσείο Ολυμπίας",
    type: "culture",
    area: "Olympia",
    x: 67,
    y: 47,
    pulse: 4,
    mood: "rainy day save",
    crowd: "medium",
    budget: "€€",
    bestTime: "hot midday",
    tags: ["museum", "culture", "indoor", "rainy"],
    short: "Good indoor move when the sun is too aggressive.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/20190507%20061%20olympia%20museum.jpg?width=1200",
  },
  {
    id: "olympic-games-museum",
    name: "Museum of Ancient Olympic Games",
    greekName: "Μουσείο Αρχαίων Ολυμπιακών Αγώνων",
    type: "culture",
    area: "Olympia",
    x: 66,
    y: 45,
    pulse: 4,
    mood: "old-school olympic lore",
    crowd: "low",
    budget: "€",
    bestTime: "midday",
    tags: ["museum", "olympics", "quick", "culture"],
    short: "Small culture hit before going back to beach mode.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Museum%20of%20the%20History%20of%20the%20Ancient%20Olympic%20Games%2C%20Archaia%20Olympia%20Greece.jpg?width=1200",
  },
  {
    id: "katakolo-port",
    name: "Katakolo Port",
    greekName: "Λιμάνι Κατακόλου",
    type: "local",
    area: "Katakolo",
    x: 20,
    y: 42,
    pulse: 8,
    mood: "port walk energy",
    crowd: "high when cruise ships arrive",
    budget: "free",
    bestTime: "sunset",
    tags: ["port", "walk", "coffee", "cruise"],
    short: "Port walk, coffee, sea air, cruise chaos, good people-watching.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Katakolo%20Port.jpg?width=1200",
  },
  {
    id: "katakolo-sunset",
    name: "Katakolo Sunset",
    greekName: "Ηλιοβασίλεμα Κατακόλου",
    type: "sunset",
    area: "Katakolo",
    x: 18,
    y: 40,
    pulse: 7,
    mood: "easy sunset spot",
    crowd: "medium",
    budget: "free",
    bestTime: "20:00",
    tags: ["sunset", "walk", "date", "photo"],
    short: "Low-effort sunset spot with port lights and sea breeze.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Katakolo-sunset.jpg?width=1200",
  },
  {
    id: "katakolo-kiani-akti",
    name: "Kiani Akti Katakolo",
    greekName: "Κυανή Ακτή Κατακόλου",
    type: "beach",
    area: "Katakolo",
    x: 19,
    y: 44,
    pulse: 6,
    mood: "quick swim near port",
    crowd: "medium",
    budget: "free",
    bestTime: "morning",
    tags: ["beach", "near-port", "quick", "swim"],
    short: "Easy beach option when you're around Katakolo and don't want a whole expedition.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Katakolo-Kiani%20Akti%20beach.jpg?width=1200",
  },
  {
    id: "kourouta-beach",
    name: "Kourouta Beach",
    greekName: "Παραλία Κουρούτας",
    type: "beach",
    area: "Kourouta",
    x: 21,
    y: 29,
    pulse: 10,
    mood: "beach all day, party later",
    crowd: "high",
    budget: "€",
    bestTime: "18:00 onwards",
    tags: ["beach", "party", "bars", "after"],
    short: "The obvious beach-party magnet. Come for sea, stay when the lights turn on.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/%CE%9A%CE%BF%CF%85%CF%81%CE%BF%CF%8D%CF%84%CE%B1%20-%20panoramio%20%281%29.jpg?width=1200",
  },
  {
    id: "kourouta-sunset",
    name: "Kourouta Sunset Strip",
    greekName: "Κουρούτα Sunset",
    type: "night",
    area: "Kourouta",
    x: 18,
    y: 28,
    pulse: 9,
    mood: "sunset into drinks",
    crowd: "high",
    budget: "€€",
    bestTime: "20:30",
    tags: ["sunset", "drinks", "after", "music"],
    short: "Where the beach slowly turns into the night plan.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Sunset%20in%20Kourouta%2C%20western%20Peloponnese%2C%20Greece.jpg?width=1200",
  },
  {
    id: "palouki-beach",
    name: "Palouki Beach",
    greekName: "Παραλία Παλούκι",
    type: "beach",
    area: "Amaliada Coast",
    x: 27,
    y: 39,
    pulse: 6,
    mood: "quieter beach just south of Kourouta",
    crowd: "medium",
    budget: "free",
    bestTime: "late afternoon",
    tags: ["beach", "camping", "quiet", "near-kourouta"],
    short: "A calmer sandy beach move near Kourouta, with a small port and camping energy.",
    imageUrl:
      "https://www.visit-olympia.gr/sites/default/files/field/image/media/2022-10/9065.jpeg",
  },
  {
    id: "agios-andreas",
    name: "Agios Andreas",
    greekName: "Άγιος Ανδρέας",
    type: "food",
    area: "Near Katakolo",
    x: 17,
    y: 38,
    pulse: 7,
    mood: "seafood and lazy drinks",
    crowd: "medium",
    budget: "€€",
    bestTime: "sunset dinner",
    tags: ["seafood", "sunset", "local", "drinks"],
    short: "Small seaside hang for food, beers, and low-stress sunset.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Sunset%20at%20Agios%20Andreas.jpg?width=1200",
  },
  {
    id: "kyllini-beach",
    name: "Kyllini Beach",
    greekName: "Παραλία Κυλλήνης",
    type: "beach",
    area: "Kyllini",
    x: 19,
    y: 12,
    pulse: 8,
    mood: "long beach energy",
    crowd: "medium",
    budget: "free",
    bestTime: "morning to sunset",
    tags: ["beach", "long", "swim", "open"],
    short: "Big beach feeling, easier to breathe than the packed spots.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20Kyllini%20Beach%2C%20Greece%20%2851224121780%29.jpg?width=1200",
  },
  {
    id: "kyllini-harbor",
    name: "Kyllini Harbor",
    greekName: "Λιμάνι Κυλλήνης",
    type: "local",
    area: "Kyllini",
    x: 16,
    y: 14,
    pulse: 6,
    mood: "ferry port movement",
    crowd: "medium",
    budget: "free",
    bestTime: "before ferry",
    tags: ["port", "ferry", "walk", "coffee"],
    short: "Ferry movement, quick coffee, sea view, people in transit.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Kyllini%20harbor.JPG?width=1200",
  },
  {
    id: "kyllini-old-beach",
    name: "Kyllini Old Beach",
    greekName: "Παραλία δίπλα στο λιμάνι",
    type: "beach",
    area: "Kyllini",
    x: 17,
    y: 16,
    pulse: 5,
    mood: "simple port swim",
    crowd: "low",
    budget: "free",
    bestTime: "morning",
    tags: ["beach", "port", "simple", "swim"],
    short: "Nothing fancy. Just a quick sea reset near the harbor.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Kyllini%20beach.JPG?width=1200",
  },
  {
    id: "arkoudi-beach",
    name: "Arkoudi Beach",
    greekName: "Παραλία Αρκούδι",
    type: "beach",
    area: "Arkoudi",
    x: 7,
    y: 26,
    pulse: 7,
    mood: "small resort beach without a big-city feel",
    crowd: "medium",
    budget: "€",
    bestTime: "sunset",
    tags: ["beach", "north", "family", "walk"],
    short: "Compact north-coast beach village for an easy swim and food after.",
    imageUrl: "https://visit-olympia.gr/sites/default/files/field/image/media/2022-10/0289.jpeg",
  },
  {
    id: "glyfa-beach",
    name: "Glyfa Beach",
    greekName: "Παραλία Γλύφας",
    type: "beach",
    area: "Pineios Coast",
    x: 13,
    y: 29,
    pulse: 6,
    mood: "wide sand, pine shade, low drama",
    crowd: "low",
    budget: "free",
    bestTime: "morning",
    tags: ["beach", "pine", "quiet", "family"],
    short:
      "A broad sandy beach between Vartholomio dunes and Arkoudi, better for space than scene.",
    imageUrl: "https://visit-olympia.gr/sites/default/files/field/image/media/2022-10/0289.jpeg",
  },
  {
    id: "loutra-kyllinis",
    name: "Loutra Kyllinis",
    greekName: "Λουτρά Κυλλήνης",
    type: "nature",
    area: "Kastro-Kyllini",
    x: 7,
    y: 24,
    pulse: 5,
    mood: "thermal-bath detour near the north coast",
    crowd: "low",
    budget: "€€",
    bestTime: "morning",
    tags: ["thermal", "spa", "north", "quiet"],
    short: "Thermal-bath area near Kyllini for a slower, non-beach reset.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Roman%20baths%2C%20Loutra%20Killinis%2C%20Greece.jpg?width=1200",
  },
  {
    id: "chlemoutsi",
    name: "Chlemoutsi Castle",
    greekName: "Κάστρο Χλεμούτσι",
    type: "culture",
    area: "Kastro-Kyllini",
    x: 28,
    y: 15,
    pulse: 6,
    mood: "castle hill flex",
    crowd: "low",
    budget: "€",
    bestTime: "golden hour",
    tags: ["castle", "view", "history", "photo"],
    short: "Castle silhouette, hill views, and a good break from the beach loop.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20Chlemoutsi.jpg?width=1200",
  },
  {
    id: "chlemoutsi-sea-view",
    name: "Chlemoutsi Sea View",
    greekName: "Χλεμούτσι Θέα",
    type: "culture",
    area: "Kastro-Kyllini",
    x: 30,
    y: 13,
    pulse: 5,
    mood: "history with horizon",
    crowd: "low",
    budget: "€",
    bestTime: "sunset",
    tags: ["view", "castle", "quiet", "sunset"],
    short: "A more cinematic angle on the castle and the Ionian horizon.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Chlemoutsi%20castle%20from%20the%20sea.jpg?width=1200",
  },
  {
    id: "vartholomio",
    name: "Vartholomio",
    greekName: "Βαρθολομιό",
    type: "local",
    area: "Pineios",
    x: 17,
    y: 24,
    pulse: 5,
    mood: "plain-town stop before the north beaches",
    crowd: "low",
    budget: "€",
    bestTime: "evening",
    tags: ["town", "cheap", "local", "north"],
    short: "A practical local stop between the inland plain and the Arkoudi/Glyfa coast.",
    imageUrl: "https://visit-olympia.gr/sites/default/files/field/image/media/2022-10/0289.jpeg",
  },
  {
    id: "gastouni",
    name: "Gastouni",
    greekName: "Γαστούνη",
    type: "local",
    area: "Pineios",
    x: 21,
    y: 25,
    pulse: 5,
    mood: "market town, coffee, errands, local week",
    crowd: "medium",
    budget: "€",
    bestTime: "morning",
    tags: ["town", "coffee", "local", "cheap"],
    short: "Real local rhythm: coffee, errands, and a useful stop before the coast.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Panagia%20Katholiki%20%28Gastouni%29%20Journal%20of%20the%20Royal%20Institute%20of%20British%20Architects%201923-12-08%20Vol%2031%20%282%29.png?width=1200",
  },
  {
    id: "lechaina",
    name: "Lechaina",
    greekName: "Λεχαινά",
    type: "local",
    area: "Andravida-Kyllini",
    x: 22,
    y: 13,
    pulse: 5,
    mood: "north-plain town, simple food and coffee",
    crowd: "low",
    budget: "€",
    bestTime: "evening",
    tags: ["town", "coffee", "north", "local"],
    short: "A small northern town stop that makes the Kyllini side feel less empty on the map.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/House%20of%20Andreas%20Karkavitsas%20at%20Lechaina.jpg?width=1200",
  },
  {
    id: "pineios-reservoir",
    name: "Pinios Reservoir",
    greekName: "Λίμνη Πηνειού",
    type: "nature",
    area: "Ilida",
    x: 43,
    y: 19,
    pulse: 5,
    mood: "inland lake, dam road, quiet views",
    crowd: "low",
    budget: "free",
    bestTime: "late afternoon",
    tags: ["lake", "dam", "nature", "quiet"],
    short: "Artificial lake and dam country northeast of Amaliada, good for a quiet inland drive.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Kaiafa%20lake.jpg?width=1200",
  },
  {
    id: "kaiafas-lake",
    name: "Kaiafas Lake",
    greekName: "Λίμνη Καϊάφα",
    type: "nature",
    area: "Zacharo",
    x: 38,
    y: 72,
    pulse: 8,
    mood: "strange lake, pine, thermal myth",
    crowd: "medium",
    budget: "free",
    bestTime: "late afternoon",
    tags: ["lake", "nature", "walk", "weird"],
    short: "Lake, pine forest, strange calm energy. Great contrast after the beach.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Kaiafa%20lake.jpg?width=1200",
  },
  {
    id: "kaiafas-sunset",
    name: "Kaiafas Sunset",
    greekName: "Καϊάφας Ηλιοβασίλεμα",
    type: "sunset",
    area: "Zacharo",
    x: 35,
    y: 74,
    pulse: 7,
    mood: "quiet cinematic sunset",
    crowd: "low",
    budget: "free",
    bestTime: "20:00",
    tags: ["sunset", "lake", "nature", "quiet"],
    short: "For when you want sunset without the beach bar noise.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Kaiafa%20Sunset.jpg?width=1200",
  },
  {
    id: "zacharo-beach",
    name: "Zacharo Beach",
    greekName: "Παραλία Ζαχάρως",
    type: "beach",
    area: "Zacharo",
    x: 23,
    y: 76,
    pulse: 8,
    mood: "huge sand, free feeling",
    crowd: "medium",
    budget: "free",
    bestTime: "sunset",
    tags: ["beach", "sunset", "long-walk", "cheap"],
    short: "Long sandy beach, big sky, less polished, more free.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/500px%20photo%20%28255278229%29.jpeg?width=1200",
  },
  {
    id: "kakovatos-beach",
    name: "Kakovatos Beach",
    greekName: "Παραλία Κακόβατου",
    type: "beach",
    area: "Kakovatos",
    x: 25,
    y: 82,
    pulse: 7,
    mood: "low-key endless beach",
    crowd: "low",
    budget: "free",
    bestTime: "late afternoon",
    tags: ["beach", "quiet", "sand", "walk"],
    short: "Low-key beach for people who don't want the obvious scene.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Beach%20of%20Kakovatos%2C%20Elis%2C%20Greece%20%281%29.jpg?width=1200",
  },
  {
    id: "kakovatos-inland",
    name: "Kakovatos Dunes",
    greekName: "Κακόβατος Αμμόλοφοι",
    type: "nature",
    area: "Kakovatos",
    x: 27,
    y: 84,
    pulse: 5,
    mood: "sand, fields, no drama",
    crowd: "low",
    budget: "free",
    bestTime: "morning",
    tags: ["nature", "beach", "quiet", "walk"],
    short: "Beach meets inland fields. Good for a quiet reset.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Looking%20inland%20from%20the%20beach%20of%20Kakovatos%2C%20Elis%2C%20Greece.jpg?width=1200",
  },
  {
    id: "giannitsochori",
    name: "Giannitsochori Beach",
    greekName: "Παραλία Γιαννιτσοχωρίου",
    type: "beach",
    area: "South Ilia",
    x: 22,
    y: 89,
    pulse: 6,
    mood: "remote-ish beach freedom",
    crowd: "low",
    budget: "free",
    bestTime: "sunset",
    tags: ["beach", "south", "quiet", "raw"],
    short: "South-coast escape when you want more space and fewer people.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Giannitsochori%20beach%20-%20panoramio.jpg?width=1200",
  },
  {
    id: "tholo-beach",
    name: "Tholo Beach",
    greekName: "Παραλία Θολό",
    type: "beach",
    area: "Zacharo South",
    x: 63,
    y: 87,
    pulse: 5,
    mood: "south-coast camping beach",
    crowd: "low",
    budget: "free",
    bestTime: "sunset",
    tags: ["beach", "south", "camping", "quiet"],
    short: "A south-coast sandy stop near Zacharo for camping vibes and more breathing room.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Beach%20of%20Kakovatos%2C%20Elis%2C%20Greece%20%281%29.jpg?width=1200",
  },
  {
    id: "samiko-acropolis",
    name: "Samiko / Samicum",
    greekName: "Σαμικό",
    type: "culture",
    area: "Kato Samiko",
    x: 39,
    y: 68,
    pulse: 4,
    mood: "ancient hill, obscure energy",
    crowd: "low",
    budget: "free",
    bestTime: "morning",
    tags: ["ancient", "hill", "hidden", "route"],
    short: "For people who like the obscure ancient-place feeling more than guided tours.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Samia%20acropolis.jpg?width=1200",
  },
  {
    id: "foloi-forest",
    name: "Foloi Forest",
    greekName: "Δάσος Φολόης",
    type: "nature",
    area: "Foloi",
    x: 72,
    y: 31,
    pulse: 8,
    mood: "mythic forest escape",
    crowd: "low",
    budget: "free",
    bestTime: "morning",
    tags: ["forest", "nature", "shade", "walk"],
    short: "Oak forest, shade, mythic quiet. The anti-beach day.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Foloi%20Forest%20-%20panoramio.jpg?width=1200",
  },
  {
    id: "foloi-deep",
    name: "Deep Foloi",
    greekName: "Βαθιά Φολόη",
    type: "nature",
    area: "Foloi",
    x: 75,
    y: 29,
    pulse: 6,
    mood: "offline walk energy",
    crowd: "low",
    budget: "free",
    bestTime: "early",
    tags: ["forest", "camping-vibe", "walk", "quiet"],
    short: "For the alternative/nature people. Bring water, leave no trash.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/%CE%94%CE%AC%CF%83%CE%BF%CF%82%20%CE%A6%CE%BF%CE%BB%CF%8C%CE%B7%CF%82%20-%20panoramio.jpg?width=1200",
  },
  {
    id: "nemouta-waterfalls",
    name: "Nemouta Waterfalls",
    greekName: "Καταρράκτες Νεμούτας",
    type: "nature",
    area: "Foloi / Erymanthos",
    x: 77,
    y: 47,
    pulse: 6,
    mood: "waterfall hike on the Erymanthos side",
    crowd: "low",
    budget: "free",
    bestTime: "spring or early autumn",
    tags: ["waterfall", "hike", "nature", "shade"],
    short: "A real inland escape: waterfall trail energy near Nemouta and the Erymanthos valley.",
    imageUrl:
      "https://justforonesummer.com/wp-content/uploads/2017/07/Nemouta-Waterfalls-2-1-2000x1333.jpg",
  },
  {
    id: "nemouta-village",
    name: "Nemouta",
    greekName: "Νεμούτα",
    type: "village",
    area: "Foloi",
    x: 75,
    y: 46,
    pulse: 4,
    mood: "mountain village base for waterfall walks",
    crowd: "low",
    budget: "€",
    bestTime: "midday",
    tags: ["village", "waterfall", "mountain", "quiet"],
    short: "Small mountain village base before or after the waterfalls.",
    imageUrl:
      "https://justforonesummer.com/wp-content/uploads/2017/07/Nemouta-Waterfalls-9-1170x780.jpg",
  },
  {
    id: "lampeia-divri",
    name: "Lampeia / Divri",
    greekName: "Λάμπεια / Δίβρη",
    type: "village",
    area: "Mountain Ilia",
    x: 77,
    y: 24,
    pulse: 4,
    mood: "cool mountain village above the heat",
    crowd: "low",
    budget: "€",
    bestTime: "summer evening",
    tags: ["village", "mountain", "cooler", "local"],
    short: "A cooler mountain-side village stop when the coast is too hot.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Foloi%20Forest%20-%20panoramio.jpg?width=1200",
  },
  {
    id: "andritsaina",
    name: "Andritsaina",
    greekName: "Ανδρίτσαινα",
    type: "village",
    area: "Andritsaina",
    x: 78,
    y: 76,
    pulse: 6,
    mood: "stone village, slow night",
    crowd: "low",
    budget: "€",
    bestTime: "evening",
    tags: ["village", "food", "slow", "local"],
    short: "Mountain village energy. Not polished, in a good way.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Andritsaina%20overview.jpg?width=1200",
  },
  {
    id: "andritsaina-streets",
    name: "Andritsaina Streets",
    greekName: "Σοκάκια Ανδρίτσαινας",
    type: "village",
    area: "Andritsaina",
    x: 80,
    y: 78,
    pulse: 5,
    mood: "stone lanes and quiet beers",
    crowd: "low",
    budget: "€",
    bestTime: "evening",
    tags: ["village", "walk", "local", "quiet"],
    short: "Good for a slow walk before food and mountain air.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Andritsaina.jpg?width=1200",
  },
  {
    id: "bassae-temple",
    name: "Temple of Apollo Epicurius",
    greekName: "Ναός Επικούριου Απόλλωνα",
    type: "culture",
    area: "Near Andritsaina",
    x: 84,
    y: 82,
    pulse: 6,
    mood: "remote monument trip",
    crowd: "low",
    budget: "€",
    bestTime: "morning",
    tags: ["unesco", "temple", "route", "remote"],
    short: "A serious detour, but the kind that makes the day feel bigger.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Temple%20of%20Apollo%20Bassae%201982.jpg?width=1200",
  },
  {
    id: "bassae-inside",
    name: "Bassae Route Stop",
    greekName: "Διαδρομή Βάσσες",
    type: "culture",
    area: "Andritsaina route",
    x: 86,
    y: 84,
    pulse: 4,
    mood: "deep culture route",
    crowd: "low",
    budget: "€",
    bestTime: "morning",
    tags: ["temple", "roadtrip", "culture", "quiet"],
    short: "For the roadtrip people who want something more than beach bars.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Bassae%20Temple%20of%20Apollo%20040911.jpg?width=1200",
  },
  {
    id: "ancient-elis",
    name: "Ancient Elis",
    greekName: "Αρχαία Ήλιδα",
    type: "culture",
    area: "Ilida",
    x: 51,
    y: 22,
    pulse: 5,
    mood: "ruins without crowds",
    crowd: "low",
    budget: "€",
    bestTime: "late afternoon",
    tags: ["ancient", "hidden", "walk", "quiet"],
    short: "Ancient site without the tourist pressure. Good quiet culture stop.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Elis%20acropolis.JPG?width=1200",
  },
  {
    id: "elis-agora",
    name: "Elis Agora",
    greekName: "Αγορά Αρχαίας Ήλιδας",
    type: "culture",
    area: "Ilida",
    x: 53,
    y: 24,
    pulse: 4,
    mood: "quiet archaeology",
    crowd: "low",
    budget: "€",
    bestTime: "morning",
    tags: ["ancient", "agora", "quiet", "culture"],
    short: "A calm archaeology stop for people who hate packed sites.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Elis%20Agora.JPG?width=1200",
  },
  {
    id: "pyrgos-centre",
    name: "Pyrgos Centre",
    greekName: "Κέντρο Πύργου",
    type: "local",
    area: "Pyrgos",
    x: 38,
    y: 39,
    pulse: 8,
    mood: "local city movement",
    crowd: "medium",
    budget: "€",
    bestTime: "evening",
    tags: ["city", "coffee", "local", "cheap"],
    short: "Not a postcard. More like where the actual local week happens.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Pyrgos%20rathaus.jpg?width=1200",
  },
  {
    id: "pyrgos-night",
    name: "Pyrgos Rex Corner",
    greekName: "Πύργος Ρεξ",
    type: "night",
    area: "Pyrgos",
    x: 39,
    y: 41,
    pulse: 7,
    mood: "local night start",
    crowd: "medium",
    budget: "€",
    bestTime: "22:00",
    tags: ["city", "night", "bars", "local"],
    short: "Start here, ask around, follow the night.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/%CE%9A%CE%B9%CE%BD%CE%B7%CE%BC%CE%B1%CF%84%CE%BF%CE%B3%CF%81%CE%AC%CF%86%CE%BF%CF%82%20%C2%AB%CE%A1%CE%AD%CE%BE%C2%BB.jpg?width=1200",
  },
  {
    id: "amaliada-square",
    name: "Amaliada Square",
    greekName: "Πλατεία Αμαλιάδας",
    type: "local",
    area: "Amaliada",
    x: 42,
    y: 26,
    pulse: 7,
    mood: "local coffee and pregame",
    crowd: "medium",
    budget: "€",
    bestTime: "21:00",
    tags: ["square", "coffee", "local", "cheap"],
    short: "Coffee, pregame, local movement before Kourouta.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/%CE%A0%CE%BB%CE%B1%CF%84%CE%B5%CE%AF%CE%B1%20%CE%91%CE%BC%CE%B1%CE%BB%CE%B9%CE%AC%CE%B4%CE%B1.jpg?width=1200",
  },
  {
    id: "skafidia",
    name: "Skafidia",
    greekName: "Σκαφιδιά",
    type: "beach",
    area: "Skafidia",
    x: 21,
    y: 36,
    pulse: 6,
    mood: "small coastal escape",
    crowd: "medium",
    budget: "€",
    bestTime: "late afternoon",
    tags: ["beach", "coast", "sunset", "chill"],
    short: "Smaller coastal energy near Pyrgos/Katakolo.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/%CE%A3%CE%BA%CE%B1%CF%86%CE%B9%CE%B4%CE%B9%CE%B1%20%CE%B7%CE%BB%CE%B5%CE%B9%CE%B1%CF%82.jpg?width=1200",
  },
  {
    id: "skafidia-monastery",
    name: "Skafidia Monastery",
    greekName: "Μονή Σκαφιδιάς",
    type: "culture",
    area: "Skafidia",
    x: 29,
    y: 46,
    pulse: 4,
    mood: "fortified monastery near the sea",
    crowd: "low",
    budget: "free",
    bestTime: "morning",
    tags: ["monastery", "culture", "coast", "quiet"],
    short: "A compact culture stop near Skafidia, close enough to combine with the coast.",
    imageUrl: "https://visitkatakolon.gr/wp-content/uploads/2015/03/monastery2.jpg",
  },
  {
    id: "korakochori",
    name: "Korakochori",
    greekName: "Κορακοχώρι",
    type: "village",
    area: "Pyrgos Coast",
    x: 27,
    y: 50,
    pulse: 4,
    mood: "coastal village between Katakolo and Pyrgos",
    crowd: "low",
    budget: "€",
    bestTime: "late afternoon",
    tags: ["village", "coast", "quiet", "wine"],
    short: "Small coastal village stop that anchors the Katakolo-to-Skafidia stretch.",
    imageUrl: "https://visitkatakolon.gr/wp-content/uploads/2015/03/mercury.jpg",
  },
  {
    id: "mercouri-estate",
    name: "Mercouri Estate",
    greekName: "Κτήμα Μερκούρη",
    type: "food",
    area: "Korakochori",
    x: 27,
    y: 50,
    pulse: 6,
    mood: "historic winery by the Katakolo coast",
    crowd: "medium",
    budget: "€€",
    bestTime: "morning tour",
    tags: ["wine", "estate", "katakolo", "food"],
    short:
      "Historic winery and estate near Korakochori, useful for a Katakolo/Olympia day that is not only ruins.",
    imageUrl: "https://visitkatakolon.gr/wp-content/uploads/2015/03/Mercouri-Estate.jpeg",
  },
  {
    id: "lechaina-zacharo-flower",
    name: "Wild Coastline",
    greekName: "Άγρια Ακτογραμμή",
    type: "nature",
    area: "Ilia Coast",
    x: 20,
    y: 62,
    pulse: 5,
    mood: "raw beach nature",
    crowd: "low",
    budget: "free",
    bestTime: "morning",
    tags: ["wild", "coast", "nature", "quiet"],
    short: "A raw coastal stretch for quiet walks, salt air, and finding your own spot.",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Pancratium%20Maritimum%20Lechaina-Zaharo%20beach%2020140816.jpg?width=1200",
  },
  {
    id: "epitalio",
    name: "Epitalio",
    greekName: "Επιτάλιο",
    type: "village",
    area: "Alfeios Plain",
    x: 46,
    y: 57,
    pulse: 4,
    mood: "plain village near the Alfeios route",
    crowd: "low",
    budget: "€",
    bestTime: "evening",
    tags: ["village", "alfeios", "local", "route"],
    short: "A real local point south of Pyrgos that helps connect the city to the Zacharo side.",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Elis%20acropolis.JPG?width=1200",
  },
];

const AVATAR_POOL = [
  "https://i.pravatar.cc/80?img=12",
  "https://i.pravatar.cc/80?img=32",
  "https://i.pravatar.cc/80?img=47",
  "https://i.pravatar.cc/80?img=58",
  "https://i.pravatar.cc/80?img=68",
  "https://i.pravatar.cc/80?img=22",
];

const statusOf = (h: number): PlaceStatus =>
  h >= 9 ? "busy" : h >= 7 ? "popular" : h >= 4 ? "active" : "quiet";

const PLACE_COORDS: Record<string, Pick<Place, "lat" | "lng">> = {
  "ancient-olympia": { lat: 37.6441431, lng: 21.6252773 },
  "olympia-stadium": { lat: 37.6392693, lng: 21.6342494 },
  "olympia-museum": { lat: 37.6434963, lng: 21.6295709 },
  "olympic-games-museum": { lat: 37.6410748, lng: 21.6255075 },
  "katakolo-port": { lat: 37.6455045, lng: 21.3249507 },
  "katakolo-sunset": { lat: 37.6493, lng: 21.3155 },
  "katakolo-kiani-akti": { lat: 37.6535, lng: 21.3189 },
  "kourouta-beach": { lat: 37.7694054, lng: 21.2938768 },
  "kourouta-sunset": { lat: 37.7678, lng: 21.2918 },
  "palouki-beach": { lat: 37.7558463, lng: 21.3063088 },
  "agios-andreas": { lat: 37.6650031, lng: 21.3097208 },
  "kyllini-beach": { lat: 37.9379579, lng: 21.1448092 },
  "kyllini-harbor": { lat: 37.9378191, lng: 21.1489917 },
  "kyllini-old-beach": { lat: 37.9348, lng: 21.1406 },
  "arkoudi-beach": { lat: 37.8472474, lng: 21.1083014 },
  "glyfa-beach": { lat: 37.826109, lng: 21.17462 },
  "loutra-kyllinis": { lat: 37.8587849, lng: 21.1129738 },
  chlemoutsi: { lat: 37.8903641, lng: 21.1412423 },
  "chlemoutsi-sea-view": { lat: 37.8912, lng: 21.138 },
  vartholomio: { lat: 37.8610449, lng: 21.2087496 },
  gastouni: { lat: 37.8507048, lng: 21.2542417 },
  lechaina: { lat: 37.9373907, lng: 21.2633204 },
  "pineios-reservoir": { lat: 37.8940004, lng: 21.4656037 },
  "kaiafas-lake": { lat: 37.5053769, lng: 21.6286574 },
  "kaiafas-sunset": { lat: 37.508, lng: 21.5805 },
  "zacharo-beach": { lat: 37.4825, lng: 21.587 },
  "kakovatos-beach": { lat: 37.455, lng: 21.598 },
  "kakovatos-inland": { lat: 37.4577879, lng: 21.6442368 },
  giannitsochori: { lat: 37.3931409, lng: 21.6881126 },
  "tholo-beach": { lat: 37.409444, lng: 21.666111 },
  "samiko-acropolis": { lat: 37.5337646, lng: 21.5984452 },
  "foloi-forest": { lat: 37.7396701, lng: 21.7077524 },
  "foloi-deep": { lat: 37.789914, lng: 21.7212628 },
  "nemouta-waterfalls": { lat: 37.6987006, lng: 21.8061752 },
  "nemouta-village": { lat: 37.7007409, lng: 21.79184 },
  "lampeia-divri": { lat: 37.8579587, lng: 21.8075223 },
  andritsaina: { lat: 37.4838364, lng: 21.9055326 },
  "andritsaina-streets": { lat: 37.4829, lng: 21.9068 },
  "bassae-temple": { lat: 37.4296358, lng: 21.9002299 },
  "bassae-inside": { lat: 37.4318507, lng: 21.899584 },
  "ancient-elis": { lat: 37.8912912, lng: 21.3735659 },
  "elis-agora": { lat: 37.8898, lng: 21.3748 },
  "pyrgos-centre": { lat: 37.6721814, lng: 21.4439156 },
  "pyrgos-night": { lat: 37.6712, lng: 21.4418 },
  "amaliada-square": { lat: 37.7979165, lng: 21.3533588 },
  skafidia: { lat: 37.698418, lng: 21.3278037 },
  "skafidia-monastery": { lat: 37.7008192, lng: 21.325745 },
  korakochori: { lat: 37.6751019, lng: 21.3144272 },
  "mercouri-estate": { lat: 37.676717759856, lng: 21.310256847083 },
  "lechaina-zacharo-flower": { lat: 37.63, lng: 21.315 },
  epitalio: { lat: 37.6270957, lng: 21.4959889 },
};

export const PLACES: Place[] = RAW_PLACES.map((p, i) => {
  const coords = PLACE_COORDS[p.id];
  if (!coords) {
    throw new Error(`Missing map coordinates for ${p.id}`);
  }

  return {
    ...(p as Omit<
      Place,
      "lat" | "lng" | "hotness" | "commentCount" | "recentPostCount" | "status" | "avatars"
    >),
    ...coords,
    hotness: p.pulse,
    commentCount: Math.max(1, p.pulse - 1 + (i % 3)),
    recentPostCount: Math.max(0, p.pulse - 2),
    status: statusOf(p.pulse),
    avatars: AVATAR_POOL.slice(
      i % 3,
      (i % 3) + Math.min(4, Math.max(2, Math.floor(p.pulse / 2.2))),
    ),
  };
});

const SAMPLE_COMMENTS: Comment[] = [
  { author: "Nikos", text: "parking is chaos after 21:00" },
  { author: "Maria", text: "worth it tho" },
  { author: "Eleni", text: "go before sunset, way calmer" },
];

export const POSTS: Post[] = [
  {
    id: "post-1",
    authorId: "nikos",
    placeId: "kourouta-beach",
    kind: "spot",
    time: "18 min ago",
    text: "Kourouta is filling up already. Music starts after sunset. Don't come too late if you want parking.",
    tags: ["beach", "tonight", "parking"],
    likes: 48,
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/%CE%9A%CE%BF%CF%85%CF%81%CE%BF%CF%8D%CF%84%CE%B1%20-%20panoramio%20%281%29.jpg?width=1200",
    comments: SAMPLE_COMMENTS.slice(0, 3),
  },
  {
    id: "post-2",
    authorId: "maria",
    placeId: "zacharo-beach",
    kind: "photo",
    time: "32 min ago",
    text: "Zacharo sunset is insane and way less packed than expected.",
    tags: ["sunset", "quiet", "cheap"],
    likes: 31,
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/500px%20photo%20%28255278229%29.jpeg?width=1200",
    comments: SAMPLE_COMMENTS.slice(0, 3),
  },
  {
    id: "post-3",
    authorId: "nikos",
    placeId: "amaliada-square",
    kind: "tip",
    time: "1h ago",
    text: "Pregame in Amaliada then Kourouta. Classic summer move.",
    tags: ["pregame", "local", "after"],
    likes: 64,
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/%CE%A0%CE%BB%CE%B1%CF%84%CE%B5%CE%AF%CE%B1%20%CE%91%CE%BC%CE%B1%CE%BB%CE%B9%CE%AC%CE%B4%CE%B1.jpg?width=1200",
    comments: SAMPLE_COMMENTS.slice(0, 3),
  },
  {
    id: "post-4",
    authorId: "eleni",
    placeId: "pyrgos-night",
    kind: "event",
    time: "tonight",
    text: "Small DJ thing near the old Rex corner. Starts late, obviously.",
    tags: ["dj", "night", "local"],
    likes: 22,
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/%CE%9A%CE%B9%CE%BD%CE%B7%CE%BC%CE%B1%CF%84%CE%BF%CE%B3%CF%81%CE%AC%CF%86%CE%BF%CF%82%20%C2%AB%CE%A1%CE%AD%CE%BE%C2%BB.jpg?width=1200",
    comments: SAMPLE_COMMENTS.slice(0, 3),
  },
  {
    id: "post-5",
    authorId: "nikos",
    placeId: "foloi-forest",
    kind: "tip",
    time: "today",
    text: "Foloi is perfect right now. Shade, quiet, no beach chaos. Bring water and don't leave trash.",
    tags: ["nature", "respect", "walk"],
    likes: 57,
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Foloi%20Forest%20-%20panoramio.jpg?width=1200",
    comments: SAMPLE_COMMENTS.slice(0, 3),
  },
  {
    id: "post-6",
    authorId: "andreas",
    placeId: "agios-andreas",
    kind: "spot",
    time: "2h ago",
    text: "Fresh fish tonight, tables outside, sunset view. No dress code nonsense.",
    tags: ["food", "sunset", "sea"],
    likes: 19,
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Sunset%20at%20Agios%20Andreas.jpg?width=1200",
    comments: SAMPLE_COMMENTS.slice(0, 2),
  },
  {
    id: "post-7",
    authorId: "maria",
    placeId: "katakolo-port",
    kind: "photo",
    time: "45 min ago",
    text: "Katakolo is touristy but the port walk is actually nice at golden hour.",
    tags: ["port", "walk", "photo"],
    likes: 27,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Katakolo%20Port.jpg?width=1200",
    comments: SAMPLE_COMMENTS.slice(0, 3),
  },
  {
    id: "post-8",
    authorId: "nikos",
    placeId: "andritsaina",
    kind: "tip",
    time: "tonight",
    text: "Village night up here. Slow food, cold beers, better temperature than the coast.",
    tags: ["village", "beer", "slow"],
    likes: 39,
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Andritsaina%20overview.jpg?width=1200",
    comments: SAMPLE_COMMENTS.slice(0, 3),
  },
];

export const EVENTS: EventItem[] = [
  {
    id: "event-1",
    title: "Beach set at Kourouta",
    placeId: "kourouta-sunset",
    time: "Tonight · 22:30",
    price: "free entry",
    vibe: "beach → after",
    tags: ["dj", "beach", "after"],
  },
  {
    id: "event-2",
    title: "Panigyri outside Amaliada",
    placeId: "amaliada-square",
    time: "Tonight · 21:30",
    price: "cheap",
    vibe: "village/local",
    tags: ["panigyri", "music", "beer"],
  },
  {
    id: "event-3",
    title: "Sunset meet at Zacharo",
    placeId: "zacharo-beach",
    time: "Today · 20:00",
    price: "free",
    vibe: "chill",
    tags: ["sunset", "beach", "quiet"],
  },
  {
    id: "event-4",
    title: "Local bar night in Pyrgos",
    placeId: "pyrgos-night",
    time: "Tonight · late",
    price: "€",
    vibe: "local night",
    tags: ["bar", "local", "after"],
  },
  {
    id: "event-5",
    title: "Forest walk morning",
    placeId: "foloi-forest",
    time: "Tomorrow · 09:00",
    price: "free",
    vibe: "nature reset",
    tags: ["forest", "walk", "morning"],
  },
];

export const ROUTES: RouteItem[] = [
  {
    id: "route-1",
    title: "Beach → Food → After",
    authorId: "eleni",
    lede: "Do this if you want the obvious Kourouta night without wasting half the day.",
    duration: "7h",
    budget: "€€",
    stops: [
      {
        time: "17:30",
        placeId: "kourouta-beach",
        title: "Arrive late",
        body: "Swim, chill, don't roast in the midday heat.",
      },
      {
        time: "21:30",
        placeId: "amaliada-square",
        title: "Pregame in the square",
        body: "Cheap food and pregame. More local than beach bar prices.",
      },
      {
        time: "23:45",
        placeId: "kourouta-sunset",
        title: "Back to Kourouta",
        body: "Follow the music. Don't overplan.",
      },
    ],
    tags: ["party", "beach", "night"],
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Sunset%20in%20Kourouta%2C%20western%20Peloponnese%2C%20Greece.jpg?width=1200",
    commentCount: 8,
    saves: 30,
  },
  {
    id: "route-2",
    title: "No-car Katakolo Day",
    authorId: "nikos",
    lede: "Cruise off, walk the port, swim, eat by the sea. No rental needed.",
    duration: "5h",
    budget: "€",
    stops: [
      {
        time: "10:00",
        placeId: "katakolo-port",
        title: "Port walk",
        body: "Coffee, sea air, watch the cruise ships dock.",
      },
      {
        time: "12:15",
        placeId: "katakolo-kiani-akti",
        title: "Quick swim",
        body: "Small beach reset close enough to walk without turning the day into logistics.",
      },
      {
        time: "19:00",
        placeId: "agios-andreas",
        title: "Seafood + drinks",
        body: "Tables outside, sunset, no dress code.",
      },
    ],
    tags: ["no car", "cruise", "walk"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Katakolo%20Port.jpg?width=1200",
    commentCount: 11,
    saves: 41,
  },
  {
    id: "route-3",
    title: "Quiet South Coast",
    authorId: "maria",
    lede: "Skip the crowds. Big sky, free beaches, sunset that ruins you for everywhere else.",
    duration: "1 day",
    budget: "free",
    stops: [
      {
        time: "17:00",
        placeId: "zacharo-beach",
        title: "Wide sand",
        body: "Big sky, fewer people, free vibes.",
      },
      {
        time: "14:00",
        placeId: "kakovatos-beach",
        title: "Low-key swim",
        body: "Skip the obvious scene. Endless beach.",
      },
      {
        time: "19:30",
        placeId: "giannitsochori",
        title: "South coast sunset",
        body: "Remote-ish. Worth the drive.",
      },
    ],
    tags: ["quiet", "beach", "sunset"],
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Beach%20of%20Kakovatos%2C%20Elis%2C%20Greece%20%281%29.jpg?width=1200",
    commentCount: 14,
    saves: 52,
  },
  {
    id: "route-4",
    title: "Forest Escape",
    authorId: "andreas",
    lede: "Trade the heat for shade. Oak trees, slow village, real mountain air.",
    duration: "half day",
    budget: "free",
    stops: [
      {
        time: "09:00",
        placeId: "foloi-forest",
        title: "Forest walk",
        body: "Shade, quiet, no beach chaos. Bring water.",
      },
      {
        time: "12:00",
        placeId: "foloi-deep",
        title: "Go deeper",
        body: "For the alternative/nature people. Leave no trash.",
      },
      {
        time: "19:00",
        placeId: "andritsaina",
        title: "Mountain village night",
        body: "Slow food, cold beers, better temperature.",
      },
    ],
    tags: ["nature", "shade", "village"],
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Foloi%20Forest%20-%20panoramio.jpg?width=1200",
    commentCount: 17,
    saves: 63,
  },
  {
    id: "route-5",
    title: "Ancient Without Boring",
    authorId: "eleni",
    lede: "Culture, but the kind you actually want to talk about after.",
    duration: "1 day",
    budget: "€€",
    stops: [
      {
        time: "10:00",
        placeId: "ancient-olympia",
        title: "Olympia at golden hour",
        body: "Ancient ruins, surprisingly walkable.",
      },
      {
        time: "14:00",
        placeId: "ancient-elis",
        title: "Hidden ruins",
        body: "Calm archaeology, no tourist pressure.",
      },
      {
        time: "18:30",
        placeId: "chlemoutsi",
        title: "Castle sunset",
        body: "Hill view, Ionian horizon, photos.",
      },
    ],
    tags: ["culture", "roadtrip", "views"],
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20the%20archaeological%20site%20of%20Ancient%20Olympia%2C%20Greece%20%2851223832734%29.jpg?width=1200",
    commentCount: 20,
    saves: 74,
  },
];

export const VIBE_CHIPS = [
  "Απόψε",
  "Beach",
  "Music",
  "Πανηγύρι",
  "Cheap",
  "Χωριό",
  "Nature",
  "After",
  "Sunset",
  "No car",
  "Locals",
];

export const STORIES = [
  { label: "Kourouta", placeId: "kourouta-beach" },
  { label: "Zacharo", placeId: "zacharo-beach" },
  { label: "Olympia", placeId: "ancient-olympia" },
  { label: "Foloi", placeId: "foloi-forest" },
  { label: "Katakolo", placeId: "katakolo-port" },
  { label: "Andritsaina", placeId: "andritsaina" },
  { label: "Kyllini", placeId: "kyllini-beach" },
];

export const AUTHORS: Author[] = [
  { id: "you", name: "You", type: "LOCAL", avatarUrl: "https://i.pravatar.cc/120?img=22" },
  {
    id: "eleni",
    name: "Eleni",
    type: "LOCAL EDITOR",
    avatarUrl: "https://i.pravatar.cc/120?img=47",
  },
  { id: "nikos", name: "Nikos", type: "LOCAL", avatarUrl: "https://i.pravatar.cc/120?img=12" },
  { id: "maria", name: "Maria", type: "TOURIST", avatarUrl: "https://i.pravatar.cc/120?img=32" },
  {
    id: "andreas",
    name: "Andreas",
    type: "BUSINESS",
    avatarUrl: "https://i.pravatar.cc/120?img=58",
  },
];

export const findAuthor = (id: string) => AUTHORS.find((a) => a.id === id) ?? AUTHORS[0];

export const typeColor: Record<PlaceType, string> = {
  beach: "#7FC8DE",
  culture: "#0E3A5B",
  nature: "#667A3D",
  food: "#E06A32",
  local: "#E06A32",
  village: "#7A4DD8",
  night: "#7A4DD8",
  sunset: "#E06A32",
};

export const authorTypeColor: Record<Author["type"], string> = {
  "LOCAL EDITOR": "#7A4DD8",
  LOCAL: "#667A3D",
  TOURIST: "#0E3A5B",
  BUSINESS: "#E06A32",
  EVENT: "#E06A32",
  EDITOR: "#7A4DD8",
};
